#!/usr/bin/env python
# coding: utf-8

# # Climate Change and Impacts in Africa
# Climate Change and Impacts in Africa
# According to the United Nations, Climate change refers to long-term shifts in temperatures and weather patterns. Such shifts can be natural, due to changes in the sun’s activity or large volcanic eruptions. But since the 1800s, human activities have been the main driver of climate change, primarily due to the burning of fossil fuels like coal, oil, and gas.
# 
# The consequences of climate change now include, among others, intense droughts, water scarcity, severe fires, rising sea levels, flooding, melting polar ice, catastrophic storms, and declining biodiversity.
# 
# creating a report on the state of climate change in Africa. And also provide insights on the impact of climate change on African regions (with four countries, one from each African region, as case studies).
# 
# Dataset
# The dataset, IEA-EDGAR CO2, is a component of the EDGAR (Emissions Database for Global Atmospheric Research) Community GHG database version 7.0 (2022) including or based on data from IEA (2021) Greenhouse Gas Emissions from Energy, www.iea.org/statistics, as modified by the Joint Research Centre. The data source was the EDGARv7.0_GHG website provided by Crippa et. al. (2022) and with DOI.
# 
# The dataset contains three sheets - IPCC 2006, 1PCC 1996, and TOTALS BY COUNTRY on the amount of CO2 (a greenhouse gas) generated by countries between 1970 and 2021. You can download the dataset from your workspace or inspect the dataset directly here.
# 
# TOTALS BY COUNTRY SHEET
# This sheet contains the annual CO2 (kt) produced between 1970 - 2021 in each country. The relevant columns in this sheet are:
# 
# Columns	Description
# C_group_IM24_sh	The region of the world
# Country_code_A3	The country code
# Name	The name of the country
# Y_1970 - Y_2021	The amount of CO2 (kt) from 1970 - 2021
# IPCC 2006
# These sheets contain the amount of CO2 by country and the industry responsible.
# 
# Columns	Description
# C_group_IM24_sh	The region of the world
# Country_code_A3	The country code
# Name	The name of the country
# Y_1970 - Y_2021	The amount of CO2 (kt) from 1970 - 2021
# ipcc_code_2006_for_standard_report_name	The industry responsible for generating CO2

# In[1]:


# importing libraries
import pandas as pd
import numpy as np
import pingouin
from sklearn.linear_model import LinearRegression
from statsmodels.regression.linear_model import OLS
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('ggplot')


# In[2]:


import os
os. getcwd()


# In[3]:


# The sheet names containing our datasets
sheet_names = ['IPCC 2006', 'TOTALS BY COUNTRY']

# The column names of the dataset starts from rows 11
# Let's skip the first 10 rows
datasets = pd.read_excel('IEA_EDGAR_CO2_1970-2021.xlsx', sheet_name = sheet_names, skiprows = 10)

# we need only the African regions
african_regions = ['Eastern_Africa', 'Western_Africa', 'Southern_Africa', 'Northern_Africa']

ipcc_2006_africa = datasets['IPCC 2006'].query('C_group_IM24_sh in @african_regions')

totals_by_country_africa = datasets['TOTALS BY COUNTRY'].query('C_group_IM24_sh in @african_regions')


# In[4]:


ipcc_2006_africa.info()


# In[5]:


ipcc_2006_africa.head()


# In[6]:


# rename columns
ipcc_2006_africa = ipcc_2006_africa.rename(columns={'C_group_IM24_sh': 'Region', 'Country_code_A3': 'Code',
                                                        'ipcc_code_2006_for_standard_report_name': 'Industry'})

totals_by_country_africa = totals_by_country_africa.rename(columns={'C_group_IM24_sh': 'Region','Country_code_A3': 'Code'})

# drop columns
ipcc_2006_africa = ipcc_2006_africa.drop(['IPCC_annex','ipcc_code_2006_for_standard_report','Substance'], axis=1)

totals_by_country_africa = totals_by_country_africa.drop(['IPCC_annex', 'Substance'], axis=1)

# Melt and clean Year column

def melt_clean(df):
    value_vars = list(filter(lambda x: x.startswith('Y_'), df.columns))
    id_vars = list(set(df.columns).difference(value_vars))

    # melt
    long = df.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='Year',
    value_name='CO2')

    # drop rows where co2 is missing
    long = long[~long.CO2.isnull()]

    # convert year to integer
    long.Year = long.Year.str.replace('Y_', '').astype(int)

    return long

ipcc_2006_africa = melt_clean(ipcc_2006_africa)
totals_by_country_africa = melt_clean(totals_by_country_africa)



# In[7]:


ipcc_2006_africa


# In[8]:


totals_by_country_africa


# ### The trend of CO2 levels across the African regions

# In[9]:


sns.lineplot(
        x='Year',
        y='CO2',
        hue='Region',
        data=totals_by_country_africa,
        errorbar=None)
plt.title('CO2 levels across the African Regions between 1970 and 2021')
plt.xlabel("Year")
plt.ylabel('CO2 (kt)');


# ### The relationship between time (Year) and CO2 levels across the African regions

# In[10]:


relationship_btw_time_CO2 = totals_by_country_africa.groupby('Region')[['Year', 'CO2']].corr(method='spearman')
relationship_btw_time_CO2


# ### Determine if there is a significant difference in the CO2 levels among the African Regions

# In[11]:


aov_results = pingouin.anova(
    data=totals_by_country_africa, 
    dv='CO2', 
    between='Region')

pw_ttest_result = pingouin.pairwise_tests(
    data=totals_by_country_africa,
    dv='CO2',
    between='Region',
    padjust="bonf").round(3)


# In[12]:


aov_results


# In[13]:


pw_ttest_result


# ### Determine the most common (top 5) industries in each African region

# In[14]:


# Group the data by Region and Industry and count the occurrences
grouped = ipcc_2006_africa.groupby(
    ["Region","Industry"]).size().reset_index(name="Count")

# Sort the data within each region group by Count in descending order
grouped = grouped.sort_values(['Region', 'Count'], ascending=[True, False])

# Get the top 5 industries for each region
top_5_industries = grouped.groupby('Region').head(5).reset_index(drop=True)
top_5_industries


# ### Determine the industry responsible for the most amount of CO2 (on average) in each African Region

# In[15]:


# emissions for each group
grouped = ipcc_2006_africa.groupby(['Region', 'Industry'])['CO2'].mean().reset_index()

# the industry with the maximum average CO2 emissions in each region
max_co2_industries = grouped.loc[grouped.groupby('Region')['CO2'].idxmax()].reset_index(drop=True)

max_co2_industries


# In[16]:


# Read the temperatures datasets containing four African countries
# One from each African Region:
# Nigeria:    West Africa
# Ethiopa :   East Africa
# Tunisia:    North Africa
# Mozambique: South Africa
temperatures = pd.read_csv('temperatures.csv')
temperatures.head(5)


# ### Prediction of the CO2 levels (at each African region) in the year 2025

# In[17]:


#Training a model
newdata = pd.DataFrame({ 'Year': 2025, 'Region': african_regions })
newdata = pd.get_dummies(newdata)


reg = LinearRegression()
target = np.log10(totals_by_country_africa['CO2'])
features = pd.get_dummies(totals_by_country_africa[['Year', 'Region']])

reg.fit(features, target)
predicted_co2 = reg.predict(newdata)
predicted_co2 = np.round(10**predicted_co2, 2)

predicted_co2


# ### To Determine if CO2 levels affect annual temperature in the selected African countries

# In[21]:


countries = ["Ethiopia", "Mozambique", "Nigeria", "Tunisia"]
selected_countries = totals_by_country_africa[['Name', 'Year', 'CO2']].query('Name in @countries')
temp_long = temperatures.melt(
    id_vars=['Year'],
    value_vars=countries,
    var_name='Name',
    value_name='Temperature')

joined = pd.merge(
    selected_countries, temp_long, on=[
        'Name', 'Year'], how='inner')
    
model_temp = OLS.from_formula(
    "Temperature ~ np.log10(CO2) + Name",
    data=joined).fit()

model_temp.summary()


# ### Relationship between Temperature and CO2

# In[19]:


joined['CO2_log'] = np.log10(joined['CO2'])
sns.scatterplot(
        x='CO2_log',
        y="Temperature",
        hue="Name",
        data=joined,)
plt.title("Relationship between Temperature and CO2")
plt.xlabel("CO2 (kt) in log base 10")
plt.ylabel("Temperatures (C)")
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5), title="Country in Each Region");


# A one unit rise in log10 CO2 leads to how many degrees rise in temperature? Answer: **1.9472** 
# 
# What is the adjusted R squared value of the model? Answer: **0.984**

# **Strong Relationship**: The analysis reveals a strong relationship between CO2 emissions and temperature, with a coefficient of 1.9472 for the log-transformed CO2 variable. This implies that for every one-unit increase in the log-transformed CO2 emissions, we expect an average temperature increase of about 1.95 degrees.
# 
# **Country-Specific Effects:** The analysis indicates that the countries in the dataset significantly affect temperature. For example, when compared to the baseline country (or reference category), Mozambique shows an average temperature increase of approximately 2.08 degrees, Nigeria shows an average increase of about 2.83 degrees, and Tunisia exhibits a decrease of approximately 1.63 degrees.
# 
# **Model Fit:** The model demonstrates an excellent fit to the data, with an R-squared value of 0.985. This indicates that about 98.5% of the variability in temperature can be explained by the variables included in the model.
# 
# **Statistical Significance:** All coefficients are statistically significant, as evidenced by their p-values being close to zero. This suggests that the relationships identified are unlikely to have occurred by random chance.
# 
# **Practical Implications:** The analysis underscores the importance of controlling CO2 emissions to manage temperature changes. A log-transformed CO2 increase of 1 unit corresponds to a substantial temperature rise of around 1.95 degrees, emphasizing the significance of sustainable practices to mitigate climate impacts.
# 
# **Regional Differences:** The temperature effects of different countries highlight regional variations. This insight can inform targeted strategies and policies for mitigating climate change impacts, tailored to the specific conditions of each region.
# 
# **Model Validation:** Additional statistical tests (Omnibus, Jarque-Bera, etc.) have been performed to validate the assumptions of the analysis, increasing our confidence in the findings.
# 
# **Limitations:** While the analysis provides valuable insights, it's important to note that it doesn't account for all potential variables influencing temperature, and there could be other confounding factors at play. Also, the model assumes a linear relationship, which might not fully capture complex interactions.
# 
# **Recommendations:** Based on these findings, it is recommended to focus on reducing CO2 emissions in order to mitigate temperature increases. Developing targeted interventions for different countries and regions can help address climate change more effectively.
# 
# **Further Research:** Consideration should be given to conducting further research to explore other potential variables that could impact temperature and to refine the model's accuracy.

# In[ ]:




